### ISSUE TITLE
Migrate To break_eternity.js

### ISSUE THREAD

**Issue by david19728** [IvarK/AntimatterDimensionsSourceCode#3384]
@IvarK @earthernsence @dan-simon @usavictor210 @aarextiaokhiao
I want to make a mod for AD:Reality and go past e9e15......
But I can't migrate to break_eternity.js!!!

**Can you migrate to it???**

**Comment by david19728** [comment]
(Note:You can put the break_eternity.js to a new branch and continue developing in master branch.)

**Comment by david19728** [comment]
(Note:You can put the break_eternity.js version to a new branch and continue developing in master branch.)

**Comment by Final0i00000000a7** [comment]
On why it's so complicated to change the name of break_eternity.js when it could be solved by changing it
(Thanks for Machine Translation)

**Comment by cyip92** [comment]
We won't be migrating from break_infinity.js to break_eternity.js on the base game for the following reasons:
- The game was thoroughly tested on break_infinity.js, and switching to break_eternity.js is basically guaranteed to introduce numerous new bugs
- Nothing in the base game goes over e9e15, so break_eternity.js is unnecessary
- Making the game support break_eternity.js instead of break_infinity.js would require a substantial rewrite of a lot of the existing code
- The performance impact from switching is unknown, and we don't want to risk making it worse when the game is already fairly heavy on Steam

I understand the enthusiasm and desire to go even larger, but making this change on the main game where it would affect all players of the game just doesn't make sense for us. The amount of work required and the potential risks are way too high for something which (in the best case) will leave the game unchanged for the vast majority of players.

**Comment by david19728** [comment]
@IvarK @earthernsence @dan-simon @usavictor210 @aarextiaokhiao @Jacorb90 @Patashu @Naruyoko 
What can you do?

**Comment by Final0i00000000a7** [comment]
Are you looking for:ExpantaNum.js

**Comment by usavictor210** [comment]
@david19728 I am trying my best to explain my position in the most polite and formal way possible.

First of all, I can say that essentially everyone involved in pre-Reality update modding did not have access to any of the Reality codebase. This means not only the developers of the Reality Update don't know how to theoretically incorporate break_eternity.js into the Reality Update, but neither Aarex, Naruyoko, Jacorb, nor I even have the slightest idea on how to make it compatible. There is simply too much work involved that we cannot handle on our own. I understand that it is possible to try to develop this compatibility if we program enough; @cyip92 never said that it wasn't possible. However, I find that Antimatter Dimensions was not focused on such a high limit, and it's possible terrible things would happen right now if number libraries were switched.

Secondly, because of the instability of number libraries, I'm not quite sure if there will be such a compatible library yet. If there is one that works, then you may prove me wrong. However, I don't believe a lot of people know how the Reality codebase works well enough to tweak it to their liking at this current point in time. From my experience, Aarex's library has been painful to work with because of how there are issues with single number values or the possible instability of it compared to break_infinity.js. Granted, that may have been due to the numerous issues in Aarex's mod, but that is another topic.

The point is that we don't know how well these libraries will work, and I'm definitely not sure if a library like ExpantaNum, let alone OmegaNum, will even work yet. The codebase was written with different intentions in mind and numbers past 1e9e15 were certainly not one of them. What you are asking for is certainly something The Modding Tree is flexible with. Antimatter Dimensions' code, in its current state, is not comfortable with anything past the limit, and I am pretty sure there is a lack of interest in actually integrating thousands of lines of code just to raise the limit of the number library right now. 

You should know that there are not many Reality mods yet, and this is something I see happening much later down the line when people get much better with experience. If people are struggling to make tabs, they are definitely not going to consider raising the number limit yet. It's a slight pain to even get node.js to work just to get the project to load client side.

So to answer: What can we do? Nothing. Nothing until we learn more about the Reality codebase and are willing to invest time and effort into making a good mod of the Reality Update.

**Comment by cyip92** [comment]
All of the active vanilla AD devs have already decided together that we will not be doing this for all of the reasons mentioned here. Asking Hevi or any of the other devs again will not give you a different response. Just because I'm the one saying "no" here, doesn't mean that going somewhere else and asking again will suddenly turn it into a "yes". You're still asking the same people, I'm just the one responding on behalf of everyone.

Additionally, please refrain from mass-notifying tons of people on GitHub, many of whom were not involved in the development of Reality. You can contact them directly on GitHub, Discord, email, or any other means, but discussion here relates to _the official version of AD with the Reality update_. Mod makers are obviously free to do whatever they want with the code, but this is the decision we have made for the official version.

And lastly - your continued insistence on having this happen, despite the responses, is something that none of the official devs want to entertain. This goes even moreso for #3385 where you yell at Hevi in all-caps that this is "very urgent and he should stop procrastinating". GitHub has a Community Code of Conduct to follow, and continuing to be disrespectful in this way is a valid reason to bar you from future discussions in this repository if we need to.
